In [ ]:
#!pip install --upgrade pip setuptools wheel
#!pip install -r ./../requirements.txt

Requirement already satisfied: pip in c:\users\pc\anaconda3\lib\site-packages (25.3)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools in c:\users\pc\anaconda3\lib\site-packages (80.9.0)
Collecting setuptools
  Using cached setuptools-82.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wheel in c:\users\pc\anaconda3\lib\site-packages (0.45.1)
Collecting wheel
  Using cached wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: packaging>=24.0 in c:\users\pc\anaconda3\lib\site-packages (from wheel) (25.0)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Using cached setuptools-82.0.0-py3-none-any.whl (1.0 MB)
Using cached wheel-0.46.3-py3-none-any.whl (30 kB)

ERROR: To modify pip, please run the following command:
C:\Users\pc\anaconda3\python.exe -m pip install --upgrade pip setuptools wheel

Requirement already satisfied: numpy==2.4.2 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 2)) (2.4.2)
Requirement already satisfied: pandas==2.3.3 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 3)) (2.3.3)
Requirement already satisfied: matplotlib==3.10.8 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 4)) (3.10.8)
Requirement already satisfied: scikit_learn==1.8.0 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: langdetect==1.0.9 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 6)) (1.0.9)
Requirement already satisfied: nltk==3.9.3 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 7)) (3.9.3)
Requirement already satisfied: wordcloud==1.9.6 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 8)) (1.9.6)
Requirement already satisfied: seaborn==0.13.2 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 9)) (0.13.2)
Requirement already satisfied: streamlit==1.54.0 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 10)) (1.54.0)
Requirement already satisfied: opencv-python==4.13.0.92 in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 11)) (4.13.0.92)
Requirement already satisfied: pillow in c:\users\pc\anaconda3\lib\site-packages (from -r ./../requirements.txt (line 12)) (12.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\anaconda3\lib\site-packages (from pandas==2.3.3->-r ./../requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\anaconda3\lib\site-packages (from pandas==2.3.3->-r ./../requirements.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\anaconda3\lib\site-packages (from pandas==2.3.3->-r ./../requirements.txt (line 3)) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (25.0)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib==3.10.8->-r ./../requirements.txt (line 4)) (3.2.5)
Requirement already satisfied: scipy>=1.10.0 in c:\users\pc\anaconda3\lib\site-packages (from scikit_learn==1.8.0->-r ./../requirements.txt (line 5)) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\pc\anaconda3\lib\site-packages (from scikit_learn==1.8.0->-r ./../requirements.txt (line 5)) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\pc\anaconda3\lib\site-packages (from scikit_learn==1.8.0->-r ./../requirements.txt (line 5)) (3.5.0)
Requirement already satisfied: six in c:\users\pc\anaconda3\lib\site-packages (from langdetect==1.0.9->-r ./../requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: click in c:\users\pc\anaconda3\lib\site-packages (from nltk==3.9.3->-r ./../requirements.txt (line 7)) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\pc\anaconda3\lib\site-packages (from nltk==3.9.3->-r ./../requirements.txt (line 7)) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\pc\anaconda3\lib\site-packages (from nltk==3.9.3->-r ./../requirements.txt (line 7)) (4.67.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (1.9.0)
Requirement already satisfied: cachetools<7,>=5.5 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (5.5.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (3.1.45)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\pc\anaconda3\lib\site-packages (from streamlit==1.54.0->-r ./../requirements.txt (line 10)) (4.0.2)
Requirement already satisfied: jinja2 in c:\users\pc\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\pc\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\pc\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (2.7.0)
Requirement already satisfied: colorama in c:\users\pc\anaconda3\lib\site-packages (from click->nltk==3.9.3->-r ./../requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\pc\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\pc\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (2026.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pc\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\pc\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\pc\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\pc\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\pc\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit==1.54.0->-r ./../requirements.txt (line 10)) (0.28.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud
import nltk
from nltk.corpus import stopwords

#Lecture des données
X_train = pd.read_csv("../data/X_train_update.csv")
y_train = pd.read_csv("../data/Y_train_CVw08PX.csv")
X_test = pd.read_csv("../data/X_test_update.csv")

# Affichage des informations sur les datasets
print(f"Info X_train : {X_train.info()}")
print(f"Info Y_train : {y_train.info()}")
print(f"Info X_test : {X_test.info()}")

#Affichage des tailles des datasets
print(f"Taille X_train : {X_train.shape}")
print(f"Taille Y_train : {y_train.shape}")
print(f"Taille X_test : {X_test.shape}")

# Affichage du nombre de classes dans la variable cible
#print(y_train['prdtypecode'].nunique())  # 27 classes
#Merge données d'entrainement
full_data = pd.merge(X_train, y_train, left_index=True, right_index=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84916 entries, 0 to 84915
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   84916 non-null  int64
 1   designation  84916 non-null  object
 2   description  55116 non-null  object
 3   productid    84916 non-null  int64
 4   imageid      84916 non-null  int64
dtypes: int64(3), object(2)
memory usage: 3.2+ MB
Info X_train : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84916 entries, 0 to 84915
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   84916 non-null  int64
 1   prdtypecode  84916 non-null  int64
dtypes: int64(2)
memory usage: 1.3 MB
Info Y_train : None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13812 entries, 0 to 13811
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   13812 non-null  int64
 1   designation  13812 non-null  object
 2   description  8926 non-null   object
 3   productid    13812 non-null  int64
 4   imageid      13812 non-null  int64
dtypes: int64(3), object(2)
memory usage: 539.7+ KB
Info X_test : None
Taille X_train : (84916, 5)
Taille Y_train : (84916, 2)
Taille X_test : (13812, 5)

In [3]:
full_data.head()

,Unnamed: 0_x,designation,description,productid,imageid,Unnamed: 0_y,prdtypecode
0,0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,3804725264,1263597046,0,10
1,1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,436067568,1008141237,1,2280
2,2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,201115110,938777978,2,50
3,3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,50418756,457047496,3,1280
4,4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,278535884,1077757786,4,2705

In [4]:


#Suppression de la colonne Unnamed: 0_y qui est une colonne d'index inutile
full_data = full_data.drop(['Unnamed: 0_y'], axis=1)

#Renomage de la colonne Unnamed: 0_x en id et mise en index de cette colonne
full_data.rename(columns={'Unnamed: 0_x': 'id'}, inplace=True)
full_data.set_index(['id'], inplace=True)

X_test.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
X_test.set_index(['id'], inplace=True)

In [5]:
#Fonction de nettoyage du texte
import re

def clean_text(text):
    if pd.isnull(text):
        return ""

    # Supprimer la ponctuation
    #text = re.sub(r'[^\w\s]', '', text)

    # Supprimer balises HTML
    text = re.sub(r'<.*?>', '', text)

    # Remplacer <br /> par un espace
    text = text.replace(r'<br />', ' ')

    # Remplacer les référence de caractère HTML
    text = text.replace(r'&amp;', '&')
    text = text.replace(r'&nbsp;', ' ')
    text = text.replace(r'&lt', '<')
    text = text.replace(r'&gt', '>')
    text = text.replace(r'&quot', '"')
    text = text.replace(r'&#39', "'")
    text = text.replace(r'&eacute', 'e')
    text = text.replace(r'&egrave', 'e')
    text = text.replace(r'&ecirc', 'e')
    
    # Convertir en minuscules
    text = text.lower()

    # Supprimer les espaces supplémentaires
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [6]:
#Nettoyage du texte
full_data['clean_designation'] = full_data['designation'].apply(clean_text)
full_data['clean_description'] = full_data['description'].apply(clean_text)

#Vérification de doublon dans les désignations et descriptions nettoyées
duplicate_designation = full_data['clean_designation'].duplicated().sum()
duplicate_description = full_data['clean_description'].duplicated().sum()

#Concaténation des désignations et descriptions nettoyées pour l'analyse de texte
full_data['text'] = full_data['clean_designation'] + ' ' + full_data['clean_description']

# Création d'un nouveau dataframe pour l'analyse de texte
test_data = full_data.drop(columns=['designation', 'description', 'productid', 'imageid','clean_designation','clean_description'], axis=1)
display(test_data.head(20))

    prdtypecode                                               text
id
0            10  olivia: personalisiertes notizbuch / 150 seite...
1          2280  journal des arts (le) n° 133 du 28/09/2001 - l...
2            50  grand stylet ergonomique bleu gamepad nintendo...
3          1280  peluche donald - europe - disneyland 2000 (mar...
4          2705  la guerre des tuques luc a des ide;es de grand...
5          2280  afrique contemporaine n° 212 hiver 2004 - doss...
6            10        christof e: bildungsprozessen auf der spur
7          2522  conquérant sept cahier couverture polypro 240 ...
8          1280         puzzle scooby-doo avec poster 2x35 pieces
9          2582  tente pliante v3s5-pro pvc blanc - 3 x 4m50 - ...
10         1560  eames inspired sxw chair - pink - black the ti...
11         1560  fauteuil chesterfield brenton 100% cuir de buf...
12         1281  peaceable kingdom wheres bear? the hide and fi...
13         1920  paire de voilages imprimés fantaisie paire de ...
14         1560  matelas mémoire de forme 180x200 x 20 cm très ...
15         2522  zenith pince agrafeuse 591 n°10 coloris noir p...
16         2403  walter scott oeuvres complètes tomes 3456 10 e...
17         2522               mod podge dishwasher safe gloss 8oz
18         1140  power rangers rouge force mystic figurine tran...
19         2280  monde illustre (le) n° 3083 du 20/01/1917 - l'...

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer

# Importation de TfidfVectorizer pour la vectorisation du texte
vectorizer = TfidfVectorizer()

# Création des ensembles d'entraînement et de test pour l'analyse de texte (20% pour le test)
X_train, X_test, y_train, y_test = train_test_split(full_data['text'], full_data['prdtypecode'], test_size=0.2, random_state=42)

# Vectorisation du texte
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [8]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn import preprocessing



# Standardisation des données de notre dataframe 
Y_train_scaled = preprocessing.scale(X_train)

print(Y_train_scaled.mean(axis=0))
 
print(Y_train_scaled.std(axis=0))
# standardisation du dataframe 
scaler = preprocessing.StandardScaler().fit(Y_train)

Y_train_scaled = scaler.transform(Y_train)


Y_test_scaled = scaler.transform(Y_test)
print(Y_test_scaled.std(axis=0))
 
print(Y_test_scaled.mean(axis=0))

ValueError: Cannot center sparse matrices: pass `with_mean=False` instead See docstring for motivation and alternatives.